import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { initializeApp, deleteApp } from '../functions/node_modules/firebase-admin/lib/app/index.js';
import { getFirestore } from '../functions/node_modules/firebase-admin/lib/firestore/index.js';
import { processRecurringExpenseAction as act, generateTemplateBills as generate } from '../functions/recurringExpenses.js';
if (!process.env.FIRESTORE_EMULATOR_HOST) throw new Error('僅允許 Emulator 測試');
const app=initializeApp({projectId:'demo-recurring-expenses'});const db=getFirestore(app);after(()=>deleteApp(app));
const t={name:'測試管理費',category:'管理費',amount:10000,currency:'JPY',day:31,startMonth:'2026-12',method:'轉帳',note:''};
test('固定支出從設定、重試、暫停到確認付款的完整流程', async()=>{
  const {id}=await act(db,'admin',{action:'saveTemplate',template:t},new Date('2026-12-01T00:00:00+08:00'));
  const billId=`${id}_2026-12`;
  await Promise.all([generate(db,id,'2026-12'),generate(db,id,'2026-12')]);
  assert.equal((await db.collection('recurringExpenseBills').where('templateId','==',id).get()).size,1);
  assert.equal((await db.collection('expenses').get()).size,0);
  await act(db,'admin',{action:'saveTemplate',id,template:{...t,amount:11000}},new Date('2026-12-10'));
  assert.equal((await db.collection('recurringExpenseBills').doc(billId).get()).data().amount,10000);
  const results=await Promise.allSettled([1,2].map(()=>act(db,'admin',{action:'confirmBill',id:billId,paidDate:'2027-01-02',amountTwd:2300})));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const expense=await db.collection('expenses').doc(`recurring_${billId}`).get();
  assert.equal(expense.data().amountTwd,2300);assert.equal(expense.data().expenseMonth,'2026-12');assert.equal(expense.data().paidAt.toDate().toISOString().slice(0,10),'2027-01-02');
  await act(db,'admin',{action:'setActive',id,active:false},new Date('2027-01-01'));
  await generate(db,id,'2027-02');assert.equal((await db.collection('recurringExpenseBills').where('templateId','==',id).get()).size,1);
  await act(db,'admin',{action:'setActive',id,active:true},new Date('2027-03-01'));
  const march=`${id}_2027-03`;
  assert.equal((await db.collection('recurringExpenseBills').doc(march).get()).data().amount,11000);
  await act(db,'admin',{action:'skipBill',id:march});await generate(db,id,'2027-03');
  assert.equal((await db.collection('recurringExpenseBills').doc(march).get()).data().status,'skipped');
  await assert.rejects(()=>act(db,'admin',{action:'confirmBill',id:march,paidDate:'2027-03-01',amountTwd:2400}));
  await generate(db,id,'2027-05');assert.equal((await db.collection('recurringExpenseBills').doc(`${id}_2027-04`).get()).exists,true);
});
